create user ddm1 identified by 1;
grant connect,resource to ddm1;

CREATE SEQUENCE ddm1.SEQ_EMPLOYEE_AUDIT
MINVALUE 1
START WITH 1
INCREMENT BY 1
CACHE 10;
-- 创建业务表（避免使用 SYSTEM 表空间，这里用 USERS）
CREATE TABLE ddm1.EMPLOYEE (
    ID       NUMBER PRIMARY KEY,
    NAME     VARCHAR2(100) NOT NULL,
    DEPT     VARCHAR2(50),
    SALARY   NUMBER(10,2),
    EMAIL    VARCHAR2(100)
) TABLESPACE USERS;

CREATE TABLE ddm1.EMPLOYEE_AUDIT (
    AUDIT_ID        NUMBER PRIMARY KEY,
    ACTION          VARCHAR2(10) NOT NULL,      -- 'INSERT', 'UPDATE', 'DELETE'
    EMP_ID          NUMBER NOT NULL,
    EMP_NAME        VARCHAR2(100),
    EMP_DEPT        VARCHAR2(50),
    EMP_SALARY      NUMBER(10,2),
    EMP_EMAIL       VARCHAR2(100),
    CHANGED_BY      VARCHAR2(30) DEFAULT USER,  -- 当前数据库用户
    CHANGE_TIME     TIMESTAMP DEFAULT SYSTIMESTAMP
) TABLESPACE USERS;

CREATE OR REPLACE TRIGGER ddm1.TRG_EMPLOYEE_AUDIT_BI
BEFORE INSERT ON ddm1.EMPLOYEE_AUDIT
FOR EACH ROW
BEGIN
    SELECT ddm1.SEQ_EMPLOYEE_AUDIT.NEXTVAL
    INTO :NEW.AUDIT_ID
    FROM dual;
END;
/

CREATE OR REPLACE TRIGGER ddm1.TRG_EMPLOYEE_AI_AUDIT
AFTER INSERT ON ddm1.EMPLOYEE
FOR EACH ROW
BEGIN
    INSERT INTO ddm1.EMPLOYEE_AUDIT (
        ACTION,
        EMP_ID,
        EMP_NAME,
        EMP_DEPT,
        EMP_SALARY,
        EMP_EMAIL
    ) VALUES (
        'INSERT',
        :NEW.ID,
        :NEW.NAME,
        :NEW.DEPT,
        :NEW.SALARY,
        :NEW.EMAIL
    );
END;
/
-- 插入一条员工记录
INSERT INTO ddm1.EMPLOYEE (ID, NAME, DEPT, SALARY, EMAIL)
VALUES (102, '张三', '研发部', 15000.00, 'zhangsan@example.com');
select * from ddm1.EMPLOYEE;
-- 查询审计日志
SELECT * FROM ddm1.EMPLOYEE_AUDIT;

-- SELECT * FROM sys.DBA_TRIGGERS WHERE TRIGGER_NAME LIKE '%EXAM%';

-- 获取触发器DDL
-- SELECT sys.DBMS_Metadata.GET_DDL('TRIGGER', 'EXAMPLE_TRIGGER', 'ddm1TEST1') AS trigger_ddl FROM dual;

-- 获取AUDI表DDL
-- SELECT sys.DBMS_Metadata.GET_DDL('TABLE', 'AUDI', 'ddm1TEST1') AS table_ddl FROM dual;