# comment: delete '#' at the beginning of a line to uncomment the line
# 注释：删除行开头的'#'号可以取消注释

[ARCHIVE_LOCAL1]  # REDO日志归档名
ARCH_TYPE         = LOCAL
# REDO日志归档类型，REALTIME/LOCAL/SYNC/ASYNC/REMOTE 分别表示实时归档/本地归档/同步归档/异步归档/远程归档
ARCH_DEST         = /opt/arch
# 归档目标,实时归档,同步归档和异步归档设置为远程数据库实例名，本地归档为归档文件存放路径
ARCH_FILE_SIZE	  = 128                                 
# 单个REDO日志归档文件大小，单位Mb，取值范围（64M~2048M），仅对本地归档有效，缺省128M
ARCH_SPACE_LIMIT  = 14000
# REDO日志归档空间限制，当所有本地归档文件达到限制值时，系统自动删除最老的归档文件                               
# 。单位Mb，0表示无空间限制，取值范围（1024M~4294967294M），仅对本地归档有效，缺省为0
[ARCHIVE_TIMELY1] 
ARCH_TYPE = TIMELY           # 实时归档
ARCH_DEST = RWC1             # 实时归档目标实例名
