cat > /tmp/db_install.rsp << EOF
[GENERAL]
RESPONSEFILE_VERSION="11.2.0"
OPERATION_TYPE="install"
[UNIX_GROUP_NAME]
UNIX_GROUP_NAME="oinstall"
[INVENTORY_LOCATION]
INVENTORY_LOCATION="/data/oraInventory"
[SELECTED_LANGUAGES]
SELECTED_LANGUAGES="zh_CN,en"
[ORACLE_HOME]
ORACLE_HOME="/data/oracle/product/11.2.0/db_1"
[ORACLE_BASE]
ORACLE_BASE="/data/oracle"
[oracle.install.db.InstallEdition]
oracle.install.db.InstallEdition="EE"
[oracle.install.db.DBA_GROUP]
oracle.install.db.DBA_GROUP="dba"
[oracle.install.db.OPER_GROUP]
oracle.install.db.OPER_GROUP="dba"
[oracle.install.db.config.starterdb.type]
oracle.install.db.config.starterdb.type="GENERAL_PURPOSE"
[oracle.install.db.config.starterdb.globalDBName]
oracle.install.db.config.starterdb.globalDBName="orcl"
[oracle.install.db.config.starterdb.SID]
oracle.install.db.config.starterdb.SID="orcl"
[oracle.install.db.config.starterdb.characterSet]
oracle.install.db.config.starterdb.characterSet="AL32UTF8"
[oracle.install.db.config.starterdb.memoryOption]
oracle.install.db.config.starterdb.memoryOption="true"
[oracle.install.db.config.starterdb.memoryLimit]
oracle.install.db.config.starterdb.memoryLimit="2048"
[oracle.install.db.config.starterdb.password.ALL]
oracle.install.db.config.starterdb.password.ALL="Secsmart#612"
[oracle.install.db.config.starterdb.automatedBackup.enable]
oracle.install.db.config.starterdb.automatedBackup.enable="false"
[SECURITY_UPDATES_VIA_MYORACLESUPPORT]
SECURITY_UPDATES_VIA_MYORACLESUPPORT="false"
[DECLINE_SECURITY_UPDATES]
DECLINE_SECURITY_UPDATES="true"
EOF